apply from: 'gradle/scripts/helpers.gradle'

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name 'CurseMaven'
                url 'https://cursemaven.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'Modrinth'
                url 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
    mavenLocal()
}

dependencies {
    runtimeOnly 'com.cleanroommc:strip-latest-forge-requirements:1.0'
    runtimeOnly 'com.cleanroommc:osxnarratorblocker:1.0'
    runtimeOnly 'curse.maven:had-enough-items-557549:4543375'

}
