# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Source Options
use_modern_java_syntax = false

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = false
show_testing_output = false

# Mod Information
mod_version = 1.1.2
root_package = com.windanesz.betterdisplays
mod_id = betterdisplays
mod_name = Better Displays
mod_jar_name = BetterDisplays

# Mod Metadata
mod_description = A mod adding modular display cases and book holders
mod_url = https://github.com/WinDanesz/BetterDisplays
mod_update_json = https://raw.githubusercontent.com/WinDanesz/BetterDisplays/1.12.2/.forge/update.json
mod_authors = WinDanesz
mod_credits =
mod_logo_path = assets/betterdisplays/textures/gui/logo.png

# Mapping Properties
mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true

# Run Configurations
minecraft_username = WinDanesz
extra_jvm_args =
extra_tweak_classes =

# Maven Publishing
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Publishing
release_type = release
publish_with_changelog = true

# CurseForge
publish_to_curseforge = false
curseforge_project_id = 514829
curseforge_debug = false

# Modrinth
publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false

# Minecraft Source Editing
change_minecraft_sources = false

# Tags
use_tags = false
tag_class_name = ${root_package}.Tags

# Access Transformers
use_access_transformer = false
access_transformer_locations = ${mod_id}_at.cfg

# Mixins
use_mixins = false
mixin_booter_version = 10.2
generate_mixins_json = false
mixin_configs = ${mod_id}
mixin_refmap = mixins.${mod_id}.refmap.json
mixin_package =

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
